// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MinalAPI.Migrations
{
    [DbContext(typeof(ShipContext))]
    [Migration("20240602011859_Migracao")]
    partial class Migracao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinhaApiCrud.Models.HistoricoLocalizacao", b =>
                {
                    b.Property<int>("IdHistorico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorico"));

                    b.Property<DateTime>("HistoricoTimestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("IdLocalizacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdMonitoramento")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdNavio")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdHistorico");

                    b.HasIndex("IdLocalizacao");

                    b.HasIndex("IdMonitoramento");

                    b.HasIndex("IdNavio");

                    b.ToTable("Historico_localizacao");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.Localizacao", b =>
                {
                    b.Property<int>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalizacao"));

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Porto")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdLocalizacao");

                    b.ToTable("Localizacao");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.MonitoramentoOperacao", b =>
                {
                    b.Property<int>("IdMonitoramento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMonitoramento"));

                    b.Property<int>("IdNavio")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdOperacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("MetricaTimestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NomeMetrica")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal?>("ValorMetrica")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdMonitoramento");

                    b.HasIndex("IdNavio");

                    b.HasIndex("IdOperacao");

                    b.ToTable("Monitoramento_operacao");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.Navio", b =>
                {
                    b.Property<int?>("IdNavio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdNavio"));

                    b.Property<int?>("CapacidadeLastro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TipoNavio")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdNavio");

                    b.ToTable("Navio");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.OperacaoLastro", b =>
                {
                    b.Property<int>("IdOperacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOperacao"));

                    b.Property<int>("IdLocalizacao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdNavio")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("OperecaoTimestamp")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("QuantidadeAgua")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TipoOperacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdOperacao");

                    b.HasIndex("IdLocalizacao");

                    b.HasIndex("IdNavio");

                    b.ToTable("Operacao_lastro");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.HistoricoLocalizacao", b =>
                {
                    b.HasOne("MinhaApiCrud.Models.Localizacao", "Localizacao")
                        .WithMany("HistoricoLocalizacoes")
                        .HasForeignKey("IdLocalizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaApiCrud.Models.MonitoramentoOperacao", "MonitoramentoOperacao")
                        .WithMany("HistoricoLocalizacaos")
                        .HasForeignKey("IdMonitoramento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaApiCrud.Models.Navio", "Navio")
                        .WithMany("HistoricoLocalizacoes")
                        .HasForeignKey("IdNavio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("MonitoramentoOperacao");

                    b.Navigation("Navio");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.MonitoramentoOperacao", b =>
                {
                    b.HasOne("MinhaApiCrud.Models.Navio", "Navio")
                        .WithMany("MonitoramentosOperacao")
                        .HasForeignKey("IdNavio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaApiCrud.Models.OperacaoLastro", "OperacaoLastro")
                        .WithMany("MonitoramentosOperacao")
                        .HasForeignKey("IdOperacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Navio");

                    b.Navigation("OperacaoLastro");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.OperacaoLastro", b =>
                {
                    b.HasOne("MinhaApiCrud.Models.Localizacao", "Localizacao")
                        .WithMany("OperacoesLastro")
                        .HasForeignKey("IdLocalizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhaApiCrud.Models.Navio", "Navio")
                        .WithMany("OperacoesLastro")
                        .HasForeignKey("IdNavio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Localizacao");

                    b.Navigation("Navio");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.Localizacao", b =>
                {
                    b.Navigation("HistoricoLocalizacoes");

                    b.Navigation("OperacoesLastro");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.MonitoramentoOperacao", b =>
                {
                    b.Navigation("HistoricoLocalizacaos");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.Navio", b =>
                {
                    b.Navigation("HistoricoLocalizacoes");

                    b.Navigation("MonitoramentosOperacao");

                    b.Navigation("OperacoesLastro");
                });

            modelBuilder.Entity("MinhaApiCrud.Models.OperacaoLastro", b =>
                {
                    b.Navigation("MonitoramentosOperacao");
                });
#pragma warning restore 612, 618
        }
    }
}
